Unix boot scripts now wait for recovery.

diff --git a/standalone/src/main/distribution/shell-scripts/bin/neo4j b/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -166,6 +166,16 @@ detectrunning() {
   newpid=${newpid:1}
 }
 
+isrecovering() {
+  lastline=`tail -1 "$NEO4J_HOME"/data/log/neo4j.0.0.log`
+  if [[ "$lastline" == *Recovery* ]]
+  then
+    return 0
+  else
+    return 1
+  fi
+}
+
 startit() {
 
   detectos
@@ -217,41 +227,52 @@ startit() {
     fi
     STARTED_PID=$( cat "$PID_FILE" )
 
-    echo -n "process [$STARTED_PID]"
+    echo -n "Process [$STARTED_PID]"
+    echo ""
 
-	if [ $WAIT = "true" ] ; then
-	echo -n "... waiting for server to be ready."
-	    x=0
-	    while ( [ $x -lt 120 ] ) ; do
-	      ## wait for start, pick up the server listening on the port
-	      detectrunning
-	      if [ $newpid ] ; then
-	         break
-	      fi
+    if [ $WAIT = "true" ] ; then
 
-	      kill -0 $STARTED_PID 2> /dev/null || break
-	      printf "."
-	      sleep 1
-	      x=$[$x +1]
-	    done
+      if ( isrecovering ) ; then
+        echo -n "Recovering from unexpected shutdown."
+        while isrecovering; do
+          printf "."
+          sleep 1
+        done
+        echo " OK."
+      fi
 
-	    if kill -0 $STARTED_PID 2>/dev/null ; then
-	    # This should never happen, we checked before we started.
-	      if [ "$newpid" != "$STARTED_PID" ] ; then
-		    rm "$PID_FILE"
-	        kill -9 $STARTED_PID
-	        echo " BAD."
-	        exit 2
-	      fi
+	    echo -n "Waiting for server to be ready."
+      x=0
+      while ( [ $x -lt 120 ] ) ; do
+        ## wait for start, pick up the server listening on the port
+        detectrunning
+        if [ $newpid ] ; then
+           break
+        fi
 
-	      echo " OK."
-	      exit 0
-	    fi
+        kill -0 $STARTED_PID 2> /dev/null || break
+        printf "."
+        sleep 1
+        x=$[$x +1]
+      done
 
-	    echo " BAD."
-	    echo "$FRIENDLY_NAME may have failed to start, please check the logs."
-	    rm "$PID_FILE"
-	    exit 1
+      if kill -0 $STARTED_PID 2>/dev/null ; then
+      # This should never happen, we checked before we started.
+        if [ "$newpid" != "$STARTED_PID" ] ; then
+	      rm "$PID_FILE"
+          kill -9 $STARTED_PID
+          echo " BAD."
+          exit 2
+        fi
+
+        echo " OK."
+        exit 0
+      fi
+
+      echo " BAD."
+      echo "$FRIENDLY_NAME may have failed to start, please check the logs."
+      rm "$PID_FILE"
+      exit 1
     else
         echo "...Started the server in the background, returning..."
     fi
